SELECT * FROM USER;
/*
INSERT INTO HINT(HINT_ID,CREATED_DATE,HINT_DESCRIPTION,HINT_TITLE,LAST_UPDATED_DATE) VALUES(100,SYSDATE(),'Hint Description 1','Hint Title 1',SYSDATE());
INSERT INTO HINT(HINT_ID,CREATED_DATE,HINT_DESCRIPTION,HINT_TITLE,LAST_UPDATED_DATE) VALUES(101,SYSDATE(),'Hint Description 2','Hint Title 2',SYSDATE());
INSERT INTO HINT(HINT_ID,CREATED_DATE,HINT_DESCRIPTION,HINT_TITLE,LAST_UPDATED_DATE) VALUES(102,SYSDATE(),'Hint Description 3','Hint Title 3',SYSDATE());
INSERT INTO HINT(HINT_ID,CREATED_DATE,HINT_DESCRIPTION,HINT_TITLE,LAST_UPDATED_DATE) VALUES(103,SYSDATE(),'Hint Description 4','Hint Title 4',SYSDATE());
INSERT INTO HINT(HINT_ID,CREATED_DATE,HINT_DESCRIPTION,HINT_TITLE,LAST_UPDATED_DATE) VALUES(104,SYSDATE(),'Hint Description 5','Hint Title 5',SYSDATE());
INSERT INTO HINT(HINT_ID,CREATED_DATE,HINT_DESCRIPTION,HINT_TITLE,LAST_UPDATED_DATE) VALUES(105,SYSDATE(),'Hint Description 6','Hint Title 6',SYSDATE());
INSERT INTO HINT(HINT_ID,CREATED_DATE,HINT_DESCRIPTION,HINT_TITLE,LAST_UPDATED_DATE) VALUES(106,SYSDATE(),'Hint Description 7','Hint Title 7',SYSDATE());
*/